name: cis_logistics_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  another_flushbar: ^1.12.30
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  dev: ^1.0.0
  device_preview: ^1.3.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.2.0
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  get_it: ^8.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  panara_dialogs: ^0.1.5
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.6.0

dev_dependencies:
  build_runner: ^2.6.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.10.0
  retrofit_generator: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: app_assets.dart
  ignore_comments: true
  prefix: null
