name: cis_logistics_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  another_flushbar: ^1.12.30
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dev: ^1.0.0
  # device_preview: ^1.3.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.6
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.0
  freezed_annotation: 2.4.4  # Keep this version for compatibility
  get_it: ^8.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  mobile_scanner: ^7.0.1
  panara_dialogs: ^0.1.5
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.0.1
  skeletonizer: ^2.1.0+1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13  
  freezed: 2.5.7        # Use stable 2.x version
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  retrofit_generator: 9.3.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/cis_logo.png"
  # adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/cis_logo_foreground.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: app_assets.dart
  ignore_comments: true
  prefix: null
